# Generated by Django 4.0 on 2021-12-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('standard', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('roll', models.IntegerField()),
            ],
        ),
    ]
