# Generated by Django 3.1.5 on 2021-12-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('standard', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('roll', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
